In [1]:
from ClasificadorPittsburgh import ClasificadorPittsburgh
from datos import Datos
from EstrategiaParticionado import ValidacionCruzada
import numpy as np 


In [2]:
TAM_POBLACION = 10
PROB_CRUCE = 0.6
PROB_MUTACION = 0.01
TASA_ELITISMO = 0.05
NUM_GENERACIONES = 100


In [3]:
estrategia = ValidacionCruzada(5)


In [4]:
tic_tac_toe = Datos("../ficheros/ConjuntosDatos/tic-tac-toe.data", True)
example2 = Datos("../ficheros/ConjuntosDatos/example2.data",True)
titanic = Datos("../ficheros/ConjuntosDatos/titanic.data",True)

In [5]:
example2.datos

array([[[ 1.,  1.,  0.],
        [ 0.,  0.,  0.],
        [ 0.,  1.,  1.],
        ..., 
        [ 1.,  1.,  0.],
        [ 0.,  1.,  1.],
        [ 1.,  1.,  0.]],

       [[ 0.,  0.,  1.],
        [ 1.,  1.,  1.],
        [ 1.,  0.,  0.],
        ..., 
        [ 0.,  0.,  1.],
        [ 1.,  0.,  0.],
        [ 0.,  0.,  1.]]])

In [6]:
titanic.datos.shape

(1046, 4)

In [7]:
tic_tac_toe.datos.shape

(958, 10)

In [8]:
tic_tac_toe.datos

array([[array([ 1.,  0.,  0.]), array([ 1.,  0.,  0.]),
        array([ 1.,  0.,  0.]), ..., array([ 0.,  1.,  0.]),
        array([ 0.,  1.,  0.]), array([ 1.,  0.])],
       [array([ 1.,  0.,  0.]), array([ 1.,  0.,  0.]),
        array([ 1.,  0.,  0.]), ..., array([ 1.,  0.,  0.]),
        array([ 0.,  1.,  0.]), array([ 1.,  0.])],
       [array([ 1.,  0.,  0.]), array([ 1.,  0.,  0.]),
        array([ 1.,  0.,  0.]), ..., array([ 0.,  1.,  0.]),
        array([ 1.,  0.,  0.]), array([ 1.,  0.])],
       ..., 
       [array([ 0.,  1.,  0.]), array([ 1.,  0.,  0.]),
        array([ 0.,  1.,  0.]), ..., array([ 0.,  1.,  0.]),
        array([ 1.,  0.,  0.]), array([ 0.,  1.])],
       [array([ 0.,  1.,  0.]), array([ 1.,  0.,  0.]),
        array([ 0.,  1.,  0.]), ..., array([ 0.,  1.,  0.]),
        array([ 1.,  0.,  0.]), array([ 0.,  1.])],
       [array([ 0.,  1.,  0.]), array([ 0.,  1.,  0.]),
        array([ 1.,  0.,  0.]), ..., array([ 1.,  0.,  0.]),
        array([ 1.,  0., 

In [9]:
clasificador = ClasificadorPittsburgh(PROB_CRUCE, 
                                      PROB_MUTACION,
                                      TASA_ELITISMO,
                                      TAM_POBLACION,
                                      NUM_GENERACIONES)
#errores = clasificador.validacion(estrategia, tic_tac_toe, clasificador)
#print( "Tasa de acierto  = ", 1 - np.mean(errores))

In [ ]:
print(1 - np.mean(clasificador.validacion(estrategia, tic_tac_toe, clasificador)))


In [ ]:
print(1 - np.mean(clasificador.validacion(estrategia, titanic, clasificador)))